# Build React app
FROM node:18 AS builder

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .
RUN npm run build


# Nginx stage
FROM nginx:alpine

COPY --from=builder /app/build /usr/share/nginx/html

# Default config (Docker)
COPY nginx.docker.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]