server {
    listen 80;

    server_name localhost;

    root /usr/share/nginx/html;
    index index.html index.htm;

    # Serve React app
    location / {
        try_files $uri /index.html;
    }

    # API requests to backend service
    location /api/ {
        proxy_pass http://chattingo-backend.chattingo.svc.cluster.local:8080/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }

    # WebSocket requests
    location /ws/ {
        proxy_pass http://chattingo-backend.chattingo.svc.cluster.local:8080/ws/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_set_header Host $host;
    }
}